# Generated by Django 3.0.5 on 2021-02-10 18:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0003_auto_20210209_2137'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='artista',
            field=models.CharField(default='artista', max_length=100, verbose_name='Artista'),
        ),
        migrations.AddField(
            model_name='article',
            name='gps',
            field=models.CharField(default='GPS', max_length=100, verbose_name='GPS'),
        ),
        migrations.AlterField(
            model_name='article',
            name='image',
            field=models.ImageField(default='null', upload_to='articles', verbose_name='Miniatura'),
        ),
        migrations.AlterField(
            model_name='article',
            name='title',
            field=models.CharField(max_length=100, verbose_name='Lugar'),
        ),
    ]
