# Generated by Django 3.0.5 on 2021-02-10 19:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0004_auto_20210210_1857'),
    ]

    operations = [
        migrations.CreateModel(
            name='Miradores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('description', models.CharField(max_length=250)),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Mirador',
                'verbose_name_plural': 'Miradores',
            },
        ),
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-created_at'], 'verbose_name': 'Street Art', 'verbose_name_plural': 'Streets Arts'},
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Ascensor', 'verbose_name_plural': 'Ascensores'},
        ),
        migrations.AlterField(
            model_name='article',
            name='artista',
            field=models.CharField(max_length=100, verbose_name='Artista'),
        ),
        migrations.AlterField(
            model_name='article',
            name='gps',
            field=models.CharField(max_length=100, verbose_name='GPS'),
        ),
    ]
