# Generated by Django 3.0.5 on 2021-02-10 20:27

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0006_auto_20210210_1950'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Miradores',
            new_name='Mira',
        ),
    ]
