# Generated by Django 3.0.5 on 2021-02-10 20:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0007_auto_20210210_2027'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mira',
            name='image',
            field=models.ImageField(default='null', upload_to='miradores', verbose_name='Miniatura'),
        ),
    ]
