# Generated by Django 3.0.5 on 2021-02-11 14:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0008_auto_20210210_2037'),
    ]

    operations = [
        migrations.CreateModel(
            name='Otros',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(default='l', max_length=100)),
                ('nombre', models.CharField(default='n', max_length=250)),
                ('descripcion', models.CharField(default='d', max_length=250)),
                ('created_at', models.DateField()),
            ],
            options={
                'verbose_name': 'Otro',
                'verbose_name_plural': 'Otros',
            },
        ),
        migrations.RemoveField(
            model_name='article',
            name='public',
        ),
    ]
