# Generated by Django 3.0.5 on 2021-02-11 14:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0010_auto_20210211_1450'),
    ]

    operations = [
        migrations.AddField(
            model_name='otros',
            name='gps',
            field=models.CharField(default='gps', max_length=100, verbose_name='GPS'),
        ),
    ]
