# Generated by Django 3.0.5 on 2021-02-11 17:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0011_otros_gps'),
    ]

    operations = [
        migrations.CreateModel(
            name='Iglesias',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('gps', models.CharField(default='gps', max_length=100, verbose_name='GPS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='null', upload_to='articles', verbose_name='Miniatura')),
            ],
            options={
                'verbose_name': 'Igleias',
                'verbose_name_plural': 'Iglesias',
            },
        ),
    ]
