# Generated by Django 3.0.5 on 2021-02-13 23:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0012_iglesias'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ascensores',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=100)),
                ('direccion', models.CharField(max_length=250)),
                ('gps', models.CharField(default='gps', max_length=100, verbose_name='GPS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='null', upload_to='articles', verbose_name='Miniatura')),
            ],
            options={
                'verbose_name': 'Ascensor',
                'verbose_name_plural': 'Ascensores',
            },
        ),
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': 'Category', 'verbose_name_plural': 'Categories'},
        ),
        migrations.AlterModelOptions(
            name='iglesias',
            options={'verbose_name': 'Igleia', 'verbose_name_plural': 'Iglesias'},
        ),
    ]
