# Generated by Django 3.0.5 on 2021-02-14 13:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0013_auto_20210213_2311'),
    ]

    operations = [
        migrations.AddField(
            model_name='mira',
            name='cerro',
            field=models.CharField(default='Cerro', max_length=100, verbose_name='nombre'),
        ),
        migrations.AlterField(
            model_name='mira',
            name='lugar',
            field=models.CharField(default='Nombre', max_length=100, verbose_name='Lugar'),
        ),
    ]
