# Generated by Django 3.0.5 on 2021-02-15 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0014_auto_20210214_1315'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascensores',
            name='content',
            field=models.TextField(default='Describir', verbose_name='Descripción'),
        ),
    ]
