# Generated by Django 3.0.5 on 2021-02-16 12:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0016_boots_escaleras'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaleras',
            name='direccion',
            field=models.CharField(default='dir', max_length=250),
        ),
    ]
