# Generated by Django 3.0.5 on 2021-02-20 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0019_auto_20210220_2126'),
    ]

    operations = [
        migrations.AddField(
            model_name='iglesias',
            name='lugar',
            field=models.CharField(default='', max_length=100),
        ),
        migrations.AlterField(
            model_name='iglesias',
            name='descripcion',
            field=models.TextField(max_length=250),
        ),
    ]
