# Generated by Django 3.0.5 on 2021-02-21 00:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0020_auto_20210220_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaleras',
            name='autor',
            field=models.CharField(default='', max_length=100),
        ),
    ]
