# Generated by Django 3.0.5 on 2021-02-21 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0021_escaleras_autor'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaleras',
            name='modelos',
            field=models.CharField(default='', max_length=100),
        ),
    ]
