# Generated by Django 3.0.5 on 2021-02-22 20:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0022_escaleras_modelos'),
    ]

    operations = [
        migrations.AddField(
            model_name='escaleras',
            name='caca',
            field=models.CharField(default='', max_length=100),
        ),
    ]
