# Generated by Django 3.0.5 on 2021-02-22 20:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0023_escaleras_caca'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='escaleras',
            name='caca',
        ),
    ]
