# Generated by Django 3.0.5 on 2021-03-14 16:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0024_remove_escaleras_caca'),
    ]

    operations = [
        migrations.AlterField(
            model_name='iglesias',
            name='image',
            field=models.ImageField(default='null', upload_to='iglesias', verbose_name='Miniatura'),
        ),
    ]
