# Generated by Django 3.0.5 on 2021-03-15 12:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0025_auto_20210314_1604'),
    ]

    operations = [
        migrations.AlterField(
            model_name='otros',
            name='image',
            field=models.ImageField(default='null', upload_to='otros', verbose_name='Miniatura'),
        ),
    ]
