# Generated by Django 3.0.5 on 2021-04-27 00:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0027_auto_20210321_1445'),
    ]

    operations = [
        migrations.AddField(
            model_name='mira',
            name='lat',
            field=models.CharField(default='lat', max_length=100, verbose_name='GPS'),
        ),
        migrations.AddField(
            model_name='mira',
            name='long',
            field=models.CharField(default='long', max_length=100, verbose_name='GPS'),
        ),
    ]
