# Generated by Django 3.0.5 on 2021-05-21 21:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0028_auto_20210427_0052'),
    ]

    operations = [
        migrations.CreateModel(
            name='Publicidad',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('publicidad', models.CharField(default='false', max_length=100)),
                ('local_nombre', models.CharField(max_length=100, verbose_name='Local')),
                ('direccion', models.CharField(max_length=100)),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.TextField(max_length=250)),
                ('gps', models.CharField(max_length=100, verbose_name='GPS')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='null', upload_to='publicidad', verbose_name='Miniatura')),
            ],
            options={
                'verbose_name': 'Publicidad',
                'verbose_name_plural': 'Publicidades',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AlterField(
            model_name='mira',
            name='lat',
            field=models.CharField(default='lat', max_length=100, verbose_name='Lat'),
        ),
        migrations.AlterField(
            model_name='mira',
            name='long',
            field=models.CharField(default='long', max_length=100, verbose_name='Long'),
        ),
    ]
