# Generated by Django 3.0.5 on 2021-05-21 21:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0029_auto_20210521_2121'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='publicidad',
            field=models.CharField(default='false', max_length=100, verbose_name='Lugar'),
        ),
    ]
