# Generated by Django 3.0.5 on 2021-05-22 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0030_article_publicidad'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='publicidad',
            field=models.BooleanField(default=False, verbose_name='Publicidad'),
        ),
    ]
