# Generated by Django 3.0.5 on 2021-05-22 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0031_auto_20210522_1443'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='lat',
            field=models.CharField(default='0', max_length=100, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='article',
            name='lon',
            field=models.CharField(default='0', max_length=100, verbose_name='Lon'),
        ),
    ]
