# Generated by Django 3.0.5 on 2021-06-01 14:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0032_auto_20210522_1632'),
    ]

    operations = [
        migrations.AddField(
            model_name='ascensores',
            name='lat',
            field=models.CharField(default='0', max_length=100, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='ascensores',
            name='lon',
            field=models.CharField(default='0', max_length=100, verbose_name='Lon'),
        ),
        migrations.AddField(
            model_name='escaleras',
            name='lat',
            field=models.CharField(default='0', max_length=100, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='escaleras',
            name='lon',
            field=models.CharField(default='0', max_length=100, verbose_name='Lon'),
        ),
        migrations.AddField(
            model_name='iglesias',
            name='lat',
            field=models.CharField(default='0', max_length=100, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='iglesias',
            name='lon',
            field=models.CharField(default='0', max_length=100, verbose_name='Lon'),
        ),
        migrations.AddField(
            model_name='otros',
            name='lat',
            field=models.CharField(default='0', max_length=100, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='otros',
            name='lon',
            field=models.CharField(default='0', max_length=100, verbose_name='Lon'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='lat',
            field=models.CharField(default='0', max_length=100, verbose_name='Lat'),
        ),
        migrations.AddField(
            model_name='publicidad',
            name='lon',
            field=models.CharField(default='0', max_length=100, verbose_name='Lon'),
        ),
    ]
