# Generated by Django 3.0.5 on 2021-06-13 15:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('miapp', '0034_auto_20210601_1533'),
    ]

    operations = [
        migrations.CreateModel(
            name='Arquitectura',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('lugar', models.CharField(max_length=100)),
                ('descripcion', models.CharField(max_length=250)),
                ('direccion', models.CharField(default='dir', max_length=250)),
                ('antecedentes', models.TextField(default='', max_length=250)),
                ('lat', models.CharField(default='0', max_length=100, verbose_name='Lat')),
                ('lon', models.CharField(default='0', max_length=100, verbose_name='Lon')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('image', models.ImageField(default='null', upload_to='arquitectura', verbose_name='Miniatura')),
            ],
            options={
                'verbose_name': 'Arquitectura',
                'verbose_name_plural': 'Arquitecturas',
            },
        ),
    ]
